apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-transitea
    receivers:
      - uid: email-transitea-receiver
        type: email
        settings:
          addresses: $ALERT_EMAIL_TO
          singleEmail: true
